; This file was auto-generated by drush make
core = 8.x
api = 2

; Modules
projects[addtoany][version] = "1.4"

projects[config_update][version] = "1.1"

projects[ctools][version] = "3.0-alpha26"

projects[default_content][version] = "1.0-alpha2"

projects[disqus][version] = "1.0-rc1"

projects[eform][version] = "1.x-dev"

projects[entityform_block][version] = "1.0-alpha2"

projects[features][version] = "3.0-beta6"

projects[file_entity][version] = "2.0-beta1"

projects[instagram_block][version] = "2.0-alpha2"

projects[pathauto][version] = "1.0-alpha3"

projects[simple_gmap][version] = "1.0"

projects[superfish][version] = "1.0-rc2"

projects[token][version] = "1.0-alpha2"

projects[views_slideshow][version] = "4.0"

; Themes
projects[adaptivetheme][version] = "1.0-rc1"

; Libraries
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"
libraries[superfish][destination] = "sites/all/libraries"
libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/archive/2.x.zip"
